version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: backend_db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: golang_boilerplate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
